### PR TITLE
Update to opencv 3

### PR DESCRIPTION
**Pull request by 183amir**
Fixes #24

### CODE REVIEW

**Comment by 183amir** [comment]
circleci is not working right now waiting for that to get online.

**Comment by kmuehlbauer** [comment]
@183amir  AFAIK, you need to activate builds in CircleCI for your personal fork (https://circleci.com/add-projects). Then also another dummy commit might be necessary.

**Comment by 183amir** [comment]
No it's because circleci is down: https://conda-forge.github.io/status/

**Comment by kmuehlbauer** [comment]
> No it's because circleci is down: https://conda-forge.github.io/status/

Oh, thanks. And sorry for the noise...

**Comment by jakirkham** [comment]
No need to be sorry @kmuehlbauer . You are both correct.

**Comment by jakirkham** [comment]
Given how long it has been since the last Caffe release and the state OpenCV was in then, it would be good to know the implications of a bump to 3.

Another thing to consider would be do we need a copy of Caffe built with OpenCV 2 and one with 3 as well?

**Comment by 183amir** [comment]
I have been compiling and using caffe with opencv 3 and it works.

**Comment by jakirkham** [comment]
Could you please provide some more detail @183amir . It works is a bit vague. What things have you tried? How have you demonstrated they work?

**Comment by 183amir** [comment]
I use caffe to run a trained caffe model from VGG group from Oxford University. And it works both from caffe here and my compiled version with opencv 3.

**Comment by 183amir** [comment]
@jakirkham following reading the saga on the status page about circleci. I enabled building pulls in circleci settings (of this project not my fork) while left secret sharing disabled. It was not possible to do it like this yesterday. I hope I didn't do anything wrong.

**Comment by 183amir** [comment]
This is building on circleci. Let me know if I can merge this.

**Comment by jakirkham** [comment]
I think you did the right thing @183amir , but it doesn't seem to be working. Could you please try turning off CircleCI on your fork and repushing? If that still doesn't work, we should bug CircleCI again.

**Comment by 183amir** [comment]
Sorry I don't have time right now to debug circle ci. I am wondering if you are ok with this pull request. There is a caffe in the defaults channel compiled with opencv 3.

**Comment by 183amir** [comment]
@jakirkham can I merge this?

**Pull request merged**
