### PR TITLE
recipe: rc4 released

### PR DESCRIPTION
**Pull request by vhffm**
Hello,

Caffe recently released version 1.0.0-rc4. This is my attempt at updating the feedstock.

Hope it's the right way of doing things (as far as I understand from the README).

### CODE REVIEW

**Comment by vhffm** [comment]
Forgot to ping maintainers: @jakirkham @183amir

**Comment by 183amir** [comment]
@vhffm please make the build number `200`.

**Comment by 183amir** [comment]
All packages linking against openblas start their build number from 200. It's a technical detail.

**Comment by vhffm** [comment]
Ok, good to know. Updated the build number now.

Thanks!

**Comment by jakirkham** [comment]
Thanks @vhffm for the PR and @183amir for the review.

**Pull request merged**
